### ISSUE TITLE
bump version failed

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/hummingbird#22]
## Description

Something went wrong:

```
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    version = __import__('hummingbird').__version__
  File "/home/travis/build/bird-house/hummingbird/hummingbird/__init__.py", line 9
    __version__ = '__version__ = '0.6.0''
                                    ^
SyntaxError: invalid syntax

```
## Environment

* Hummingbird version used, if any: 0.6.0
* Python version, if any:
* Operating System:

**Comment by cehbrecht** [comment]
fixed by PR #24.
