### ISSUE TITLE
Warnings and errors in log file

### ISSUE THREAD

**Issue by fklemme** [bird-house/hummingbird#7]
Every call to Hummingbird fills the log file with a bunch of warnings and errors:

```
2015-10-19 09:56:20 [22447] [DEBUG] GET /wps
PyWPS [2015-10-19 09:56:20,323] WARNING: Could not import process [<class malleefowl.process.WPSProcess at 0x7f55a64f5ae0>]: TypeError('__init__() takes at least 4 arguments (1 given)',)
PyWPS [2015-10-19 09:56:20,324] WARNING: Could not import process [<class malleefowl.process.WPSProcess at 0x7f55a64f5ae0>]: TypeError('__init__() takes at least 4 arguments (1 given)',)
PyWPS [2015-10-19 09:56:20,324] WARNING: Could not import process [<class malleefowl.process.WPSProcess at 0x7f55a64f5ae0>]: TypeError('__init__() takes at least 4 arguments (1 given)',)
PyWPS [2015-10-19 09:56:20,325] WARNING: Could not import process [<class malleefowl.process.WPSProcess at 0x7f55a64f5ae0>]: TypeError('__init__() takes at least 4 arguments (1 given)',)
PyWPS [2015-10-19 09:56:20,326] WARNING: Could not import process [<class malleefowl.process.WPSProcess at 0x7f55a64f5ae0>]: TypeError('__init__() takes at least 4 arguments (1 given)',)
PyWPS [2015-10-19 09:56:20,327] WARNING: Could not import process [<class malleefowl.process.WPSProcess at 0x7f55a64f5ae0>]: TypeError('__init__() takes at least 4 arguments (1 given)',)
PyWPS [2015-10-19 09:56:20,327] WARNING: Could not import process [<class malleefowl.process.WPSProcess at 0x7f55a64f5ae0>]: TypeError('__init__() takes at least 4 arguments (1 given)',)
Traceback (most recent call last):
  File "/home/fklemme/.conda/envs/birdhouse/lib/python2.7/site-packages/pywps/Wps/__init__.py", line 173, in _init_from_directory
    [processSources.__name__])
  File "/home/fklemme/Repositories/hummingbird/processes/wps_stormtrack.py", line 2, in <module>
    from c3stormtrack.processing import Stormtrack
ImportError: No module named c3stormtrack.processing
PyWPS [2015-10-19 09:56:20,328] WARNING: Could not import processes from 'processes': ImportError('No module named c3stormtrack.processing',)
Traceback (most recent call last):
  File "/home/fklemme/.conda/envs/birdhouse/lib/python2.7/site-packages/pywps/Wps/__init__.py", line 173, in _init_from_directory
    [processSources.__name__])
  File "/home/fklemme/Repositories/hummingbird/processes/wps_ncplot.py", line 8, in <module>
    from mpl_toolkits.basemap import Basemap
  File "/home/fklemme/.conda/envs/birdhouse/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 30, in <module>
    from mpl_toolkits.basemap import pyproj
ImportError: cannot import name pyproj
PyWPS [2015-10-19 09:56:20,330] WARNING: Could not import processes from 'processes': ImportError('cannot import name pyproj',)
 - - [19/Oct/2015:09:56:20 +0200] "GET /wps?version=1.0.0&request=GetCapabilities&service=WPS HTTP/1.0" 200 - "-" "python-requests/2.6.0 CPython/2.7.10 Linux/4.1.10-200.fc22.x86_64"
```

**Comment by cehbrecht** [comment]
this is a duplicate: https://github.com/bird-house/malleefowl/issues/14
